{
 "title": "General",
 "description": "Información general y avanzada del servidor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "OS_Disk", "query": "sda2" },
   { "name": "hostname", "query": "server" },
   { "name": "DeviceDisk_pool", "query": "2TB:6TB" },
   { "name": "Disk1", "query": "sda" },
   { "name": "Disk2", "query": "sdb" },
   { "name": "Disk3", "query": "sdc" },
   { "name": "Chip_Graphic_Card", "query": "nouveau-pci-0900" },
   { "name": "Chip_CPU", "query": "k10temp-pci-00c3" },
   { "name": "Speedtest_server", "query": "30481" },
   { "name": "Folder1", "query": "/media/storage/Plex/Anime" },
   {
    "name": "Folder2",
    "query": "/media/storage/home/vinanrra/Backups"
   },
   {
    "name": "Folder3",
    "query": "/media/storage/home/vinanrra/Docker/Plex/peliculas"
   },
   {
    "name": "Folder4",
    "query": "/media/storage/home/vinanrra/Docker/Plex/tv"
   },
   { "name": "Folder5", "query": "/home/vinanrra/Docker" },
   {
    "name": "Folder6",
    "query": "/media/storage/home/vinanrra/Docker/Plex/descargas/Ratio"
   }
  ]
 },
 "panels": [
  { "title": "Estado rápido", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tiempo Activo",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Contenedores Totales",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 1 },
   "targets": [
    {
     "alias": "Espacio Discos",
     "measurement": "disk",
     "query": "SELECT last(\"free\") AS \"Free\", last(\"used\") AS \"Used\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/Disk1') AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$DeviceDisk_pool$/" }
     ]
    },
    {
     "alias": "Espacio SO",
     "measurement": "disk",
     "query": "SELECT last(\"free\") AS \"Free\", last(\"used\") AS \"Used\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/Disk1') AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Contenedores Activos",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Activos",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "targets": [
    {
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "targets": [
    {
     "measurement": "swap",
     "query": "SELECT \"swap_cached\" FROM \"mem\" WHERE (\"host\" = 'AlexNAS') AND $timeFilter",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Contenedores Inactivos",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperaturas",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 10, "y": 9 },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=~", "value": "/^$Chip_CPU$/" }
     ]
    },
    {
     "alias": "Gráfica",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=~", "value": "/^$Chip_Graphic_Card$/" }
     ]
    },
    {
     "alias": "Disco Duro - 6TB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hddtemp",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Disk3$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Uso de CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Media CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "CPU0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu0" }
     ]
    },
    {
     "alias": "CPU1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu1" }
     ]
    },
    {
     "alias": "CPU2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu2" }
     ]
    },
    {
     "alias": "CPU3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu3" }
     ]
    },
    {
     "alias": "CPU4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu4" }
     ]
    },
    {
     "alias": "CPU5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu5" }
     ]
    },
    {
     "alias": "CPU6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu6" }
     ]
    },
    {
     "alias": "CPU7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu7" }
     ]
    },
    {
     "alias": "CPU8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu8" }
     ]
    },
    {
     "alias": "CPU9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu9" }
     ]
    },
    {
     "alias": "CPU10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu10" }
     ]
    },
    {
     "alias": "CPU11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu11" }
     ]
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU Soft IRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "CPU System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "CPU User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "CPU IO/Wait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Carga del Sistema",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Carga Sistema (1min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Carga Sistema (5min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Carga Sistema (15min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Red y Memoria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Velocidad de Descarga",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "query": "SELECT mean(\"download\")  / 1000024 FROM \"speed_test_results\" WHERE (\"server\" = '7387') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$Speedtest_server$/" }
     ]
    }
   ]
  },
  {
   "title": "Velocidad de Subida",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "query": "SELECT mean(\"download\")  / 1000024 FROM \"speed_test_results\" WHERE (\"server\" = '7387') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$Speedtest_server$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping Actual",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "query": "SELECT mean(\"download\")  / 1000024 FROM \"speed_test_results\" WHERE (\"server\" = '7387') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$Speedtest_server$/" }
     ]
    }
   ]
  },
  {
   "title": "Actividad de Red",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Recibido",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 1000024" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Enviado",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ " / 1000024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uso de Memoria",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "En uso",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Libre",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Discos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Discos Aumento Diario",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 49 },
   "format": "decbytes",
   "valueName": "diff",
   "targets": [
    {
     "alias": "Growth",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$DeviceDisk_pool$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 16, "w": 4, "x": 5, "y": 49 },
   "targets": [
    {
     "alias": "Almacenamiento",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$DeviceDisk_pool$/" }
     ]
    },
    {
     "alias": "SSD SO",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatura de discos",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 49 },
   "targets": [
    {
     "alias": "Disco Duro - 6TB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hddtemp",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Disk3$/" }
     ]
    }
   ]
  },
  {
   "title": "Espacio de almacenamiento",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 49 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Anime",
     "measurement": "filecount",
     "query": "SELECT \"total\" FROM \"Tautulli\" WHERE (\"section_name\" = 'Filmer') AND $timeFilter",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "directory", "operator": "=~", "value": "/^$Folder1$/" }
     ]
    },
    {
     "alias": "Backups",
     "measurement": "filecount",
     "query": "SELECT \"total\" FROM \"Tautulli\" WHERE (\"section_name\" = 'Filmer') AND $timeFilter",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "directory", "operator": "=~", "value": "/^$Folder2$/" }
     ]
    },
    {
     "alias": "Películas",
     "measurement": "filecount",
     "query": "SELECT \"total\" FROM \"Tautulli\" WHERE (\"section_name\" = 'Filmer') AND $timeFilter",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "directory", "operator": "=~", "value": "/^$Folder3$/" }
     ]
    },
    {
     "alias": "Series TV",
     "measurement": "filecount",
     "query": "SELECT \"total\" FROM \"Tautulli\" WHERE (\"section_name\" = 'Filmer') AND $timeFilter",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "directory", "operator": "=~", "value": "/^$Folder4$/" }
     ]
    },
    {
     "alias": "Docker",
     "measurement": "filecount",
     "query": "SELECT \"total\" FROM \"Tautulli\" WHERE (\"section_name\" = 'Filmer') AND $timeFilter",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "directory", "operator": "=~", "value": "/^$Folder5$/" }
     ]
    },
    {
     "alias": "Ratio",
     "measurement": "filecount",
     "query": "SELECT \"total\" FROM \"Tautulli\" WHERE (\"section_name\" = 'Filmer') AND $timeFilter",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "directory", "operator": "=~", "value": "/^$Folder6$/" }
     ]
    }
   ]
  },
  {
   "title": "Discos Aumento Semanal",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 53 },
   "format": "decbytes",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$DeviceDisk_pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Discos Aumento Mensual",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 57 },
   "format": "decbytes",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$DeviceDisk_pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Posibilidad de fallos",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 57 },
   "targets": [
    {
     "alias": "Cumulative Chance of Failure",
     "measurement": "failure_rate",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "cumulative" }
     ]
    },
    {
     "alias": "Data 1 Drive (8tb)",
     "measurement": "failure_rate",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "/dev/sdd" }
     ]
    },
    {
     "alias": "Data 2 Drive (8tb)",
     "measurement": "failure_rate",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "/dev/sda" }
     ]
    },
    {
     "alias": "Data 3 Drive (2tb)",
     "measurement": "failure_rate",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "/dev/sdc" }
     ]
    },
    {
     "alias": "Parity 1 Drive (8tb)",
     "measurement": "failure_rate",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "/dev/sdb" }
     ]
    }
   ]
  },
  {
   "title": "Discos Aumento Anual",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 61 },
   "format": "decbytes",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$DeviceDisk_pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Ratio Discos - Lectura",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "SSD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Disk1$/" }
     ]
    },
    {
     "alias": "Disco Duro - 2TB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Disk2$/" }
     ]
    },
    {
     "alias": "Disco Duro - 6TB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Disk3$/" }
     ]
    }
   ]
  },
  {
   "title": "Ratio Discos -  Escritura",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "SSD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Disk1$/" }
     ]
    },
    {
     "alias": "Disco Duro - 6TB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Disk3$/" }
     ]
    },
    {
     "alias": "Disco Duro - 2TB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Disk2$/" }
     ]
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 74 },
   "targets": [
    {
     "alias": "Contenedores Activos",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Contenedores en pausa",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Contenedores Inactivos",
     "measurement": "docker",
     "query": "SELECT \"n_containers_paused\" FROM \"docker\" WHERE (\"host\" = 'server') AND $timeFilter",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Imagenes",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_images" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Uso de RAM - Docker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "!=", "value": "total" }
     ]
    }
   ]
  },
  {
   "title": "Uso CPU Docker",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       { "params": [ " / 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Tiempo Activo",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "uptime_ns" ], "type": "field" },
       { "params": [ " / 3600000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_image", "operator": "!=", "value": "all" }
     ]
    }
   ]
  }
 ]
}